name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test-lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install
        run: npm ci
      - name: Audit
        run: npm run audit
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
  test-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install
        working-directory: ./cli
        run: npm ci
      - name: Audit
        working-directory: ./cli
        run: npm run audit
      - name: Lint
        working-directory: ./cli
        run: npm run lint
      - name: Test
        working-directory: ./cli
        run: npm test
